name: Arduino CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # Set the environment variable
    steps:

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20  # Upgrade Node.js version
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0
      with:
        arduino-cli-version: 0.34.2
    - name: Compile Arduino Sketch
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli compile --fqbn arduino:avr:uno Arduino_clock.ino
